### ISSUE TITLE
Not work with Komodo IDE 8.5.3

### ISSUE THREAD

**Issue by Defman21** [davestewart/komodo-autocode#11]
When I'm trying to drag the xpi file from build, i'm get a error: "Autocode is incompatible with Komodo IDE 8.5.3".

**Comment by davestewart** [comment]
I'll take a look at this.

**Comment by davestewart** [comment]
The 1.1 version published at https://community.activestate.com/node/7280 should work just fine, and I've just pushed this to this repo. You can also find the updated 1.1 .xpi in the _deploy folder.
