### ISSUE TITLE
add @author for functions document

### ISSUE THREAD

**Issue by harpreetsb** [davestewart/komodo-autocode#14]
sometimes one file may contain many developer working on it.
can you add @author  to function document?

**Comment by davestewart** [comment]
Already in there :)

See http://xjsfl.com/support/setup/komodo/autocode#customising-content

**Comment by harpreetsb** [comment]
also to note that toolbox does not show the "Autocode" folder since Komodo edit 9 i guess.
![selection_006](https://cloud.githubusercontent.com/assets/6584304/9346982/3c2d175c-4641-11e5-8c2c-63120acf08d5.jpg)

**Comment by harpreetsb** [comment]
@davestewart anything?
